services:
  - type: web
    name: park
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: parking_system.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: GUNICORN_WORKERS
        value: "3"
      - key: GUNICORN_THREADS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: parking-db
    databaseName: parking
    plan: free 